baseurl: https://kosirurska.github.io
languageCode: en-us
title: Urška Košir
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Hi"
      url: "/"
      weight: 1
    - name: "Blog"
      url: "/blog/"
      weight: 2
    - name: "About my work"
      url: "/work/"
      weight: 3
    - name: "Publications"
      url: "/cv/Publication_master.pdf"
      # url: "/cv/cv_urska_website_apr2022.pdf"
      weight: 4
    - name: "Code"
      url: "/code/"

params:
  description: "DPhil @Oxford University | Experimental psychology, Public Health"
  footer: "&copy; [Dr. Košir](/) 2021 | [email](mailto:dr.urska.kosir@gmail.com) | [LinkdIn](https://www.linkedin.com/in/urska-kosir/) | [Google Scholar](https://scholar.google.com/citations?user=xobwcaQAAAAJ&hl=en) | [GitHub](https://github.com/kosirurska)"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"

markup:
  goldmark:
    renderer:
      unsafe: true
