---
title: Work Areas
disable_comments: true
---

## ADOLESCENT and YOUNG ADULT ONCOLOGY

I first became interested in Adolescents and Young Adults (AYA) when I shadowed and volunteered as a student at Smilow Yale-New Haven Cancer Hospital. I had the chance to observe the entire patient pathway on the pediatric as well as adult wards. What struck me was that, despite often being more tragic cases, pediatric ward had a much more upbeat energy. 


### Fertility preservation in young people with cancer in Europe

I have started collaborating with [**Youth Cancer Europe**](https://www.youthcancereurope.org/) in 2019. I help with patient advocacy and advise on research agenda. This past year we launched a pan-European study on Fertility preservation services - this includes a comprehensive review of the exisitng sources, an online survey, and a qualitative part with individual patient interviews.

To read and learn more about the study click [**here**](https://osf.io/sr37b/). Some of the preliminary findings have been discussed at the World Cancer Congress in Geneva, Switzerland (18 - 20 October, 2022). More insights based on the results of the online survey will be shared at the European Cancer Organization Summit in November. We will post them here as well.


## PATIENT ADVOCACY


